// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJJ4WcucskNXN7P6OBrCIXc4LjRLgR9Ek',
    appId: '1:938391243558:web:0d2aecfc429987c2704fe7',
    messagingSenderId: '938391243558',
    projectId: 'studentplaner-d3910',
    authDomain: 'studentplaner-d3910.firebaseapp.com',
    storageBucket: 'studentplaner-d3910.firebasestorage.app',
    measurementId: 'G-0SK1D9M6FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAasehRzpnoXCZFfV3A86kYtfvgy8CbDdc',
    appId: '1:938391243558:android:b8791f5aeefa2501704fe7',
    messagingSenderId: '938391243558',
    projectId: 'studentplaner-d3910',
    storageBucket: 'studentplaner-d3910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgryakTQUg5Qxa4WR7tqM00BgXH4qxkfY',
    appId: '1:938391243558:ios:bb1aaab1876dec3c704fe7',
    messagingSenderId: '938391243558',
    projectId: 'studentplaner-d3910',
    storageBucket: 'studentplaner-d3910.firebasestorage.app',
    iosBundleId: 'com.example.studentPlannerReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgryakTQUg5Qxa4WR7tqM00BgXH4qxkfY',
    appId: '1:938391243558:ios:bb1aaab1876dec3c704fe7',
    messagingSenderId: '938391243558',
    projectId: 'studentplaner-d3910',
    storageBucket: 'studentplaner-d3910.firebasestorage.app',
    iosBundleId: 'com.example.studentPlannerReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJJ4WcucskNXN7P6OBrCIXc4LjRLgR9Ek',
    appId: '1:938391243558:web:240ad9bed9cf32ac704fe7',
    messagingSenderId: '938391243558',
    projectId: 'studentplaner-d3910',
    authDomain: 'studentplaner-d3910.firebaseapp.com',
    storageBucket: 'studentplaner-d3910.firebasestorage.app',
    measurementId: 'G-2T8D6LT9NV',
  );
}
